---
backend: pacman
update_db: false
update_system: false
skip_if_no_internet: false
operations:
  - localInstall:
      - /var/cache/calamares/packages/@@KERNEL_PACKAGE@@
      - /var/cache/calamares/packages/@@HEADERS_PACKAGE@@
      - /var/cache/calamares/packages/@@MACFANCTLD_PACKAGE@@
      - /var/cache/calamares/packages/@@SUPPORT_PACKAGE@@
