---
dontChroot: false
timeout: 60
script:
  - command: "/usr/bin/pacman -Q plasma-desktop plasma-login-manager plasma-nm networkmanager"
  - command: "/usr/bin/systemctl enable macfanctld.service"
  - command: "/usr/bin/systemctl enable NetworkManager.service"
  - command: "/usr/bin/systemctl enable plasmalogin.service"
  - command: "/usr/bin/systemctl set-default graphical.target"
  - command: "/usr/bin/systemctl is-enabled macfanctld.service"
  - command: "/usr/bin/systemctl is-enabled NetworkManager.service"
  - command: "/usr/bin/systemctl is-enabled plasmalogin.service"
