---
dontChroot: false
timeout: 60
script:
  - command: "/bin/bash /var/cache/calamares/packages/macpro-verify-packages.sh --kernel-name linux-macpro61 --kernel-version @@KERNEL_VERSION@@ --headers-name linux-macpro61-headers --headers-version @@HEADERS_VERSION@@ --macfanctld-name macfanctld --macfanctld-version @@MACFANCTLD_VERSION@@ --support-name macpro61-support --support-version @@SUPPORT_VERSION@@"
