# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Use only the vetted package groups shipped in the image.
---

groupsUrl:
 - file:///etc/calamares/modules/netinstall.yaml

required: true

label:
 sidebar: "Packages"
 sidebar[de]: "Pakete"
 sidebar[fi]: "Paketit"
 sidebar[fr]: "Paquets"
 sidebar[it]: "Pacchetti"
 sidebar[sp]: "Paquetes"
 sidebar[ru]: "Пакеты"
 sidebar[zh_CN]: "软件包"
 sidebar[ja]: "パッケージ"
 sidebar[sv]: "Paket"
 sidebar[pt_BR]: "Pacotes"
 title: "Additional packages"
 title[ru]: "Доп. пакеты"
